### ISSUE TITLE
[ docs ] - mistake in code snippet

### ISSUE THREAD

**Issue by mzeeshan3597** [nextui-org/tailwind-variants#111]
hello there... while exploring ur website. i saw this code error at this [page](https://www.tailwind-variants.org/docs/slots) in last snippet

=> bug
```css
const { base, tab } = tab({ color: "primary" });
```
=> correct
```css
const { base, tab } = card({ color: "primary" });
```
